name: Deploy React Frontend to Azure App Service

on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**' ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: EAD-Frontend
  NODE_VERSION: '20.x'
  REACT_APP_API_URL: https://ead-backend-hya6gkbfgrawecae.canadacentral-01.azurewebsites.net/api

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build
        run: npm run build
        working-directory: frontend
        env:
          REACT_APP_API_URL: ${{ env.REACT_APP_API_URL }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: frontend/build
          publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
